### PR TITLE
So apparently `#pragma once` does work

### PR DESCRIPTION
**Pull request by Genora51**
Yeah idk anymore apparently `#pragma once`  _does_ work on RobotC, and I no longer trust the VEX forums to give me up-to-date information on anything anymore.

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
what does this do and is it different from the old way (

```c
#ifndef CHANGEVARS
 #define CHANGEVARS
```
)
if so how

**Comment by Genora51** [comment]
It's only slightly different
What it does is ensure that a file only gets imported once, and any
subsequent imports into the main file are ignored.

**Comment by aDotInTheVoid** [comment]
and what does 
``` c
#ifndef CHANGEVARS
#define CHANGEVARS  
 ```

do

**Comment by Genora51** [comment]
Pretty much the same
The difference is that pragma prevents import while ifndef removes content,
but the file is still imported so robotc gives me dodgy warnings

**Pull request merged**
